# Generated by Django 5.1.8 on 2025-06-04 12:43

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lazer", "0002_violationsubmission_created_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="violationsubmission",
            name="captured_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
