# Generated by Django 5.1.8 on 2025-06-05 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lazer", "0003_violationsubmission_captured_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="violationsubmission",
            name="image",
            field=models.ImageField(upload_to="lazer/violations"),
        ),
    ]
