# Generated by Django 5.1.8 on 2025-06-16 22:42

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lazer", "0004_alter_violationsubmission_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="violationsubmission",
            name="submission_id",
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
