# Generated by Django 5.1.8 on 2025-06-17 04:04

import django.db.models.deletion
from django.db import migrations, models

import lazer.models


class Migration(migrations.Migration):

    dependencies = [
        ("lazer", "0005_violationsubmission_submission_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="ViolationReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("date_observed", models.CharField()),
                ("time_observed", models.CharField()),
                ("make", models.CharField()),
                ("model", models.CharField(blank=True, null=True)),
                ("body_style", models.CharField()),
                ("vehicle_color", models.CharField()),
                ("violation_observed", models.CharField()),
                ("occurrence_frequency", models.CharField()),
                ("block_number", models.CharField()),
                ("street_name", models.CharField()),
                ("zip_code", models.CharField()),
                ("additional_information", models.CharField(blank=True, null=True)),
                (
                    "screenshot_before_submit",
                    models.ImageField(
                        blank=True, null=True, upload_to=lazer.models.report_image_upload_to
                    ),
                ),
                (
                    "screenshot_after_submit",
                    models.ImageField(
                        blank=True, null=True, upload_to=lazer.models.report_image_upload_to
                    ),
                ),
                (
                    "screenshot_success",
                    models.ImageField(
                        blank=True, null=True, upload_to=lazer.models.report_image_upload_to
                    ),
                ),
                (
                    "screenshot_error",
                    models.ImageField(
                        blank=True, null=True, upload_to=lazer.models.report_image_upload_to
                    ),
                ),
                (
                    "screenshot_final",
                    models.ImageField(
                        blank=True, null=True, upload_to=lazer.models.report_image_upload_to
                    ),
                ),
                (
                    "submission",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="lazer.violationsubmission"
                    ),
                ),
            ],
        ),
    ]
