# Generated by Django 5.1.8 on 2025-06-17 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lazer", "0006_violationreport"),
    ]

    operations = [
        migrations.AddField(
            model_name="violationreport",
            name="submitted",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
