# Generated by Django 5.1.14 on 2025-12-16 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lazer", "0010_add_service_id_to_violation_report"),
    ]

    operations = [
        migrations.AddField(
            model_name="violationreport",
            name="submission_response",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
