# Generated by Django 5.1.14 on 2025-12-18 14:04

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import lazer.models


class Migration(migrations.Migration):

    dependencies = [
        ("lazer", "0011_violationreport_submission_response"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="LazerWrapped",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "share_token",
                    models.CharField(
                        db_index=True,
                        default=lazer.models.generate_share_token,
                        max_length=64,
                        unique=True,
                    ),
                ),
                ("year", models.IntegerField()),
                ("total_submissions", models.IntegerField(default=0)),
                ("total_reports", models.IntegerField(default=0)),
                ("violations_by_type", models.JSONField(default=dict)),
                ("top_streets", models.JSONField(default=list)),
                ("top_zip_codes", models.JSONField(default=list)),
                ("reports_by_month", models.JSONField(default=dict)),
                ("first_report_date", models.DateField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lazer_wrapped",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-year", "-created_at"],
                "unique_together": {("user", "year")},
            },
        ),
    ]
