# Generated by Django 5.1.14 on 2025-12-18 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lazer", "0012_lazer_wrapped"),
    ]

    operations = [
        migrations.AddField(
            model_name="lazerwrapped",
            name="longest_streak",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="lazerwrapped",
            name="longest_streak_end",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="lazerwrapped",
            name="longest_streak_reports",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="lazerwrapped",
            name="longest_streak_start",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="lazerwrapped",
            name="top_day_count",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="lazerwrapped",
            name="top_day_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
