# Generated by Django 5.1.14 on 2025-12-18 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lazer", "0013_lazer_wrapped_streak_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="lazerwrapped",
            name="avg_reports",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="lazerwrapped",
            name="percentile",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="lazerwrapped",
            name="rank",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="lazerwrapped",
            name="total_users",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
