# Generated by Django 5.1.14 on 2025-12-18 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lazer", "0014_lazer_wrapped_community_stats"),
    ]

    operations = [
        migrations.AddField(
            model_name="lazerwrapped",
            name="percent_of_total",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="lazerwrapped",
            name="total_community_reports",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
