# Generated by Django 5.1.14 on 2025-12-28 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lazer", "0015_lazer_wrapped_percent_of_total"),
    ]

    operations = [
        migrations.AddField(
            model_name="lazerwrapped",
            name="community_top_make_model",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="lazerwrapped",
            name="community_top_make_model_count",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="lazerwrapped",
            name="user_top_make_model",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="lazerwrapped",
            name="user_top_make_model_count",
            field=models.IntegerField(default=0),
        ),
    ]
