# Generated by Django 5.1.14 on 2025-12-28 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lazer", "0016_lazerwrapped_community_top_make_model_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="lazerwrapped",
            name="community_top_make_model",
        ),
        migrations.RemoveField(
            model_name="lazerwrapped",
            name="community_top_make_model_count",
        ),
        migrations.RemoveField(
            model_name="lazerwrapped",
            name="user_top_make_model",
        ),
        migrations.RemoveField(
            model_name="lazerwrapped",
            name="user_top_make_model_count",
        ),
        migrations.AddField(
            model_name="lazerwrapped",
            name="top_community_vehicles",
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name="lazerwrapped",
            name="top_user_vehicles",
            field=models.JSONField(default=list),
        ),
    ]
