# Generated by Django 5.1.15 on 2026-01-18 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("lazer", "0019_banner"),
        ("lazer", "0020_violationreport_redacted_image"),
    ]

    operations = []
