# Generated by Django 5.1.8 on 2025-04-12 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0013_shirtorder_location_shirtorder_shipping_method"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="mailjet_contact_id",
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
