# Generated by Django 5.1.8 on 2025-10-08 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0020_shirtorder_product_type_alter_shirtorder_fit"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="newsletter_opt_in",
            field=models.BooleanField(
                default=False,
                help_text="Subscribe to Philly Bike Action's monthly newsletter.",
                verbose_name="Newsletter",
            ),
        ),
    ]
