# Generated by Django 4.2.20 on 2025-03-27 11:22

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0004_rename_wordpress_slug_scheduledevent_slug_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="scheduledevent",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="scheduledevent",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
