# Generated by Django 5.1.8 on 2025-04-12 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0005_scheduledevent_created_at_scheduledevent_updated_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="eventsignin",
            name="mailjet_contact_id",
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
