# Generated by Django 5.1.8 on 2025-04-12 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0006_eventsignin_mailjet_contact_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="eventsignin",
            name="mailchimp_contact_id",
        ),
    ]
