# Generated by Django 5.1.8 on 2025-05-28 18:20

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0002_projectapplication_thread_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="projectapplication",
            name="approved",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="projectapplication",
            name="archived",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="projectapplication",
            name="channel_id",
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name="projectapplication",
            name="mentor_id",
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name="projectapplication",
            name="nay_votes",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=32), blank=True, default=list, size=None
            ),
        ),
        migrations.AddField(
            model_name="projectapplication",
            name="voting_thread_id",
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name="projectapplication",
            name="yay_votes",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=32), blank=True, default=list, size=None
            ),
        ),
    ]
