# Generated by Django 5.1.8 on 2025-06-01 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0003_projectapplication_approved_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="projectapplication",
            name="approved_by",
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name="projectapplication",
            name="vote_initiator",
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
