# Generated by Django 5.1.8 on 2025-06-01 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0004_projectapplication_approved_by_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="projectapplication",
            name="project_lead_id",
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
