# Generated by Django 5.1.8 on 2025-06-01 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0005_projectapplication_project_lead_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="projectapplication",
            name="archived_by",
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
