# Generated by Django 5.1.8 on 2025-06-02 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0006_projectapplication_archived_by"),
    ]

    operations = [
        migrations.AddField(
            model_name="projectapplication",
            name="approved_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="projectapplication",
            name="archived_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
