# Generated by Django 4.2.20 on 2025-03-24 17:53

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cms", "0005_alter_cmsstreampage_body"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cmsstreampage",
            name="body",
            field=wagtail.fields.StreamField(
                [("card", 4), ("paragraph", 6), ("html", 7), ("table", 8)],
                block_lookup={
                    0: ("wagtail.images.blocks.ImageBlock", [], {}),
                    1: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {"choices": [("left", "Left"), ("right", "Right")]},
                    ),
                    2: ("wagtail.blocks.CharBlock", (), {"required": False}),
                    3: ("wagtail.blocks.RichTextBlock", (), {}),
                    4: (
                        "wagtail.blocks.StructBlock",
                        [[("image", 0), ("image_side", 1), ("header", 2), ("text", 3)]],
                        {
                            "features": [
                                "anchor-identifier",
                                "h2",
                                "h3",
                                "h4",
                                "bold",
                                "italic",
                                "ol",
                                "ul",
                                "hr",
                                "link",
                                "document-link",
                                "image",
                                "embed",
                                "code",
                                "blockquote",
                            ]
                        },
                    ),
                    5: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {"choices": [("left", "Left"), ("center", "Center"), ("right", "Right")]},
                    ),
                    6: (
                        "wagtail.blocks.StructBlock",
                        [[("alignment", 5), ("paragraph", 3)]],
                        {
                            "features": [
                                "anchor-identifier",
                                "h2",
                                "h3",
                                "h4",
                                "bold",
                                "italic",
                                "ol",
                                "ul",
                                "hr",
                                "link",
                                "document-link",
                                "image",
                                "embed",
                                "code",
                                "blockquote",
                            ]
                        },
                    ),
                    7: ("wagtail.blocks.RawHTMLBlock", (), {}),
                    8: (
                        "wagtail.contrib.table_block.blocks.TableBlock",
                        (),
                        {
                            "table_options": {
                                "contextMenu": [
                                    "row_above",
                                    "row_below",
                                    "---------",
                                    "col_left",
                                    "col_right",
                                    "---------",
                                    "remove_row",
                                    "remove_col",
                                    "---------",
                                    "undo",
                                    "redo",
                                    "---------",
                                    "copy",
                                    "cut",
                                    "---------",
                                    "alignment",
                                ],
                                "editor": "text",
                                "renderer": "html",
                            }
                        },
                    ),
                },
            ),
        ),
    ]
