# Generated by Django 4.2.20 on 2025-03-26 01:35

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wagtailimages", "0027_image_description"),
        ("cms", "0006_alter_cmsstreampage_body"),
    ]

    operations = [
        migrations.AddField(
            model_name="homepage",
            name="body_background",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="wagtailimages.image",
            ),
        ),
        migrations.AddField(
            model_name="homepage",
            name="hero_background",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="wagtailimages.image",
            ),
        ),
        migrations.AlterField(
            model_name="homepage",
            name="body",
            field=wagtail.fields.StreamField(
                [("homepagecard", 3), ("paragraph", 5), ("html", 6)],
                block_lookup={
                    0: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {"choices": [("left", "Left"), ("right", "Right")]},
                    ),
                    1: ("wagtail.blocks.CharBlock", (), {}),
                    2: ("wagtail.blocks.RichTextBlock", (), {}),
                    3: (
                        "wagtail.blocks.StructBlock",
                        [[("text_side", 0), ("title", 1), ("subtitle", 1), ("text", 2)]],
                        {
                            "features": [
                                "anchor-identifier",
                                "h2",
                                "h3",
                                "h4",
                                "bold",
                                "italic",
                                "ol",
                                "ul",
                                "hr",
                                "link",
                                "document-link",
                                "image",
                                "embed",
                                "code",
                                "blockquote",
                            ]
                        },
                    ),
                    4: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {"choices": [("left", "Left"), ("center", "Center"), ("right", "Right")]},
                    ),
                    5: (
                        "wagtail.blocks.StructBlock",
                        [[("alignment", 4), ("paragraph", 2)]],
                        {
                            "features": [
                                "anchor-identifier",
                                "h2",
                                "h3",
                                "h4",
                                "bold",
                                "italic",
                                "ol",
                                "ul",
                                "hr",
                                "link",
                                "document-link",
                                "image",
                                "embed",
                                "code",
                                "blockquote",
                            ]
                        },
                    ),
                    6: ("wagtail.blocks.RawHTMLBlock", (), {}),
                },
            ),
        ),
    ]
