# Generated by Django 4.2.20 on 2025-03-26 11:54

import wagtail.admin.forms.choosers
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cms", "0007_homepage_body_background_homepage_hero_background_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="homepage",
            name="hero_buttons",
            field=wagtail.fields.StreamField(
                [("button", 13)],
                block_lookup={
                    0: ("wagtail.blocks.CharBlock", (), {}),
                    1: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("page", "Page"),
                                ("file", "File"),
                                ("custom_url", "Custom URL"),
                                ("email", "Email"),
                                ("anchor", "Anchor"),
                                ("phone", "Phone"),
                            ],
                            "classname": "link_choice_type_selector",
                            "label": "Link to",
                            "required": False,
                        },
                    ),
                    2: (
                        "wagtail.blocks.PageChooserBlock",
                        (),
                        {"form_classname": "page_link", "label": "Page", "required": False},
                    ),
                    3: (
                        "wagtail.documents.blocks.DocumentChooserBlock",
                        (),
                        {"form_classname": "file_link", "label": "File", "required": False},
                    ),
                    4: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "form_classname": "custom_url_link url_field",
                            "label": "Custom URL",
                            "max_length": 300,
                            "required": False,
                            "validators": [
                                wagtail.admin.forms.choosers.URLOrAbsolutePathValidator()
                            ],
                        },
                    ),
                    5: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "form_classname": "anchor_link",
                            "label": "#",
                            "max_length": 300,
                            "required": False,
                        },
                    ),
                    6: ("wagtail.blocks.EmailBlock", (), {"required": False}),
                    7: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "form_classname": "phone_link",
                            "label": "Phone",
                            "max_length": 30,
                            "required": False,
                        },
                    ),
                    8: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {
                            "form_classname": "new_window_toggle",
                            "label": "Open in new window",
                            "required": False,
                        },
                    ),
                    9: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("link_to", 1),
                                ("page", 2),
                                ("file", 3),
                                ("custom_url", 4),
                                ("anchor", 5),
                                ("email", 6),
                                ("phone", 7),
                                ("new_window", 8),
                            ]
                        ],
                        {},
                    ),
                    10: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {"choices": [("pink", "Pink"), ("green", "Green")]},
                    ),
                    11: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {"choices": [("full", "Full"), ("half", "Half")]},
                    ),
                    12: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": (
                                "A FontAwesome icon name, see "
                                '<a href="https://fontawesome.com/search?ic=free">here</a> '
                                "for list of options"
                            ),
                            "required": False,
                        },
                    ),
                    13: (
                        "wagtail.blocks.StructBlock",
                        [[("text", 0), ("url", 9), ("color", 10), ("width", 11), ("icon", 12)]],
                        {},
                    ),
                },
                default=[],
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="homepage",
            name="hero_buttons_cta",
            field=models.CharField(default="Join the Action!", max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="homepage",
            name="hero_text",
            field=models.TextField(
                default="Philly Bike Action is a 501(c)4 non-profit run entirely by volunteers."
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="homepage",
            name="hero_title",
            field=models.TextField(default="Safe, Protected Bike Lanes for Philadelphia"),
            preserve_default=False,
        ),
    ]
