# Generated by Django 4.2.20 on 2025-03-26 20:40

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cms", "0009_alter_cmsstreampage_body"),
    ]

    operations = [
        migrations.AlterField(
            model_name="homepage",
            name="hero_text",
            field=wagtail.fields.RichTextField(),
        ),
    ]
