# Generated by Django 4.2.20 on 2025-03-27 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cms", "0010_alter_homepage_hero_text"),
    ]

    operations = [
        migrations.AddField(
            model_name="cmsstreampage",
            name="show_title",
            field=models.BooleanField(default=True),
        ),
    ]
