# Generated by Django 5.1.8 on 2025-06-10 12:30

import wagtail.fields
from django.db import migrations

import cms.models


class Migration(migrations.Migration):

    dependencies = [
        ("cms", "0013_alter_cmsstreampage_body"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cmsstreampage",
            name="body",
            field=wagtail.fields.StreamField(
                [
                    ("card", 4),
                    ("paragraph", 6),
                    ("html", 7),
                    ("table", 8),
                    ("newsletter_signup", 9),
                    ("display_card_block", 11),
                ],
                block_lookup={
                    0: ("wagtail.images.blocks.ImageBlock", [], {}),
                    1: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {"choices": [("left", "Left"), ("right", "Right")]},
                    ),
                    2: ("wagtail.blocks.CharBlock", (), {"required": False}),
                    3: ("wagtail.blocks.RichTextBlock", (), {}),
                    4: (
                        "wagtail.blocks.StructBlock",
                        [[("image", 0), ("image_side", 1), ("header", 2), ("text", 3)]],
                        {
                            "features": [
                                "anchor-identifier",
                                "h2",
                                "h3",
                                "h4",
                                "bold",
                                "italic",
                                "ol",
                                "ul",
                                "hr",
                                "link",
                                "document-link",
                                "image",
                                "embed",
                                "code",
                                "blockquote",
                            ]
                        },
                    ),
                    5: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {"choices": [("left", "Left"), ("center", "Center"), ("right", "Right")]},
                    ),
                    6: (
                        "wagtail.blocks.StructBlock",
                        [[("alignment", 5), ("paragraph", 3)]],
                        {
                            "features": [
                                "anchor-identifier",
                                "h2",
                                "h3",
                                "h4",
                                "bold",
                                "italic",
                                "ol",
                                "ul",
                                "hr",
                                "link",
                                "document-link",
                                "image",
                                "embed",
                                "code",
                                "blockquote",
                            ]
                        },
                    ),
                    7: ("wagtail.blocks.RawHTMLBlock", (), {}),
                    8: (
                        "wagtail.contrib.table_block.blocks.TableBlock",
                        (),
                        {
                            "table_options": {
                                "contextMenu": [
                                    "row_above",
                                    "row_below",
                                    "---------",
                                    "col_left",
                                    "col_right",
                                    "---------",
                                    "remove_row",
                                    "remove_col",
                                    "---------",
                                    "undo",
                                    "redo",
                                    "---------",
                                    "copy",
                                    "cut",
                                    "---------",
                                    "alignment",
                                ],
                                "editor": "text",
                                "renderer": "html",
                            }
                        },
                    ),
                    9: ("wagtail.blocks.StructBlock", [[]], {}),
                    10: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {"choices": cms.models.get_collections, "label": "Collection to display"},
                    ),
                    11: (
                        "wagtail.blocks.StructBlock",
                        [[("collection", 10), ("card_count_description", 2)]],
                        {},
                    ),
                },
            ),
        ),
    ]
