# Generated by Django 4.2.20 on 2025-03-21 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("aliases", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="alias",
            name="enable_smtp",
            field=models.BooleanField(
                default=False, help_text="Should the user have SMTP sending credentials?"
            ),
        ),
        migrations.AddField(
            model_name="alias",
            name="mailgun_smtp_password",
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
