# Generated by Django 5.1.13 on 2025-11-10 14:54

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("elections", "0004_alter_nominee_board_responsibilities_acknowledged"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="election",
            name="at_large_seats_count",
            field=models.IntegerField(default=5, help_text="Number of at-large seats"),
        ),
        migrations.AddField(
            model_name="election",
            name="district_seat_min_voters",
            field=models.IntegerField(
                default=5,
                help_text="Minimum voters in a district required to activate that district's seat",
            ),
        ),
        migrations.AddField(
            model_name="election",
            name="district_seat_min_votes",
            field=models.IntegerField(
                default=5,
                help_text="Minimum votes from district members required to win district seat",
            ),
        ),
        migrations.AddField(
            model_name="election",
            name="district_seats_count",
            field=models.IntegerField(
                default=10, help_text="Number of district-reserved seats (one per district 1-10)"
            ),
        ),
        migrations.CreateModel(
            name="Ballot",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("submitted_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "election",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ballots",
                        to="elections.election",
                    ),
                ),
                (
                    "voter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ballots",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-submitted_at"],
                "unique_together": {("election", "voter")},
            },
        ),
        migrations.CreateModel(
            name="Question",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("question_text", models.TextField(help_text="The question to ask voters")),
                (
                    "order",
                    models.IntegerField(
                        default=0, help_text="Display order (lower numbers appear first)"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "election",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="questions",
                        to="elections.election",
                    ),
                ),
            ],
            options={
                "ordering": ["order", "created_at"],
                "unique_together": {("election", "order")},
            },
        ),
        migrations.CreateModel(
            name="QuestionVote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("answer", models.BooleanField(help_text="True = Yes, False = No")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "ballot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="question_votes",
                        to="elections.ballot",
                    ),
                ),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="votes",
                        to="elections.question",
                    ),
                ),
            ],
            options={
                "unique_together": {("ballot", "question")},
            },
        ),
        migrations.CreateModel(
            name="Vote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "ballot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="candidate_votes",
                        to="elections.ballot",
                    ),
                ),
                (
                    "nominee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="votes",
                        to="elections.nominee",
                    ),
                ),
            ],
            options={
                "unique_together": {("ballot", "nominee")},
            },
        ),
    ]
