# Generated by Django 5.1.13 on 2025-11-10 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("elections", "0005_election_at_large_seats_count_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="description",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Optional description or context for the question",
            ),
        ),
    ]
