# Generated by Django 5.1.13 on 2025-11-10 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("elections", "0006_question_description"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="election",
            name="district_seats_count",
        ),
    ]
