# Generated by Django 5.1.13 on 2025-11-10 16:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("elections", "0007_remove_election_district_seats_count"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="ballot",
            index=models.Index(
                fields=["election", "-submitted_at"], name="elections_b_electio_5c5dc2_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="vote",
            index=models.Index(fields=["ballot"], name="elections_v_ballot__b6f74f_idx"),
        ),
        migrations.AddIndex(
            model_name="vote",
            index=models.Index(fields=["nominee"], name="elections_v_nominee_863bd0_idx"),
        ),
    ]
