# Generated by Django 5.1.14 on 2025-11-21 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("elections", "0008_ballot_elections_b_electio_5c5dc2_idx_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="ballot",
            name="had_votes",
            field=models.BooleanField(
                blank=True,
                help_text=(
                    "Whether this ballot had at least one vote " "(set when election is closed)"
                ),
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="nominee",
            name="final_district_vote_count",
            field=models.IntegerField(
                blank=True,
                help_text=(
                    "Votes received from nominee's home district " "(set when election is closed)"
                ),
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="nominee",
            name="final_vote_count",
            field=models.IntegerField(
                blank=True,
                help_text="Total votes received (set when election is closed)",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="question",
            name="final_no_votes",
            field=models.IntegerField(
                blank=True, help_text="Total no votes (set when election is closed)", null=True
            ),
        ),
        migrations.AddField(
            model_name="question",
            name="final_yes_votes",
            field=models.IntegerField(
                blank=True, help_text="Total yes votes (set when election is closed)", null=True
            ),
        ),
    ]
