# Generated by Django 4.2.9 on 2024-03-23 21:15

import uuid

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models

import pbaabp.models


class Migration(migrations.Migration):

    dependencies = [
        ("campaigns", "0003_campaign_wordpress_id_alter_campaign_content"),
    ]

    operations = [
        migrations.CreateModel(
            name="Petition",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("title", models.CharField(max_length=512)),
                ("slug", models.SlugField(blank=True, null=True)),
                ("letter", models.TextField()),
                ("send_email", models.BooleanField(default=False)),
                (
                    "email_to",
                    models.TextField(blank=True, default=[], null=True),
                ),
                (
                    "email_cc",
                    models.TextField(blank=True, default=[], null=True),
                ),
                (
                    "signature_fields",
                    pbaabp.models.ChoiceArrayField(
                        base_field=models.CharField(
                            blank=True,
                            choices=[
                                ("comment", "Comment"),
                                ("first_name", "First Name"),
                                ("last_name", "Last Name"),
                                ("email", "E-mail"),
                                ("postal_address_line_1", "Address Line 1"),
                                ("postal_address_line_2", "Address Line 2"),
                                ("city", "City"),
                                ("state", "State"),
                                ("zip_code", "Zip Code"),
                            ],
                            max_length=128,
                            null=True,
                        ),
                        blank=True,
                        null=True,
                        size=None,
                    ),
                ),
                (
                    "campaign",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="petitions",
                        to="campaigns.campaign",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PetitionSignature",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("comment", models.TextField(blank=True, null=True)),
                ("first_name", models.CharField(blank=True, max_length=64, null=True)),
                ("last_name", models.CharField(blank=True, max_length=64, null=True)),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                (
                    "postal_address_line_1",
                    models.CharField(
                        blank=True, max_length=128, null=True, verbose_name="Address line 1"
                    ),
                ),
                (
                    "postal_address_line_2",
                    models.CharField(
                        blank=True, max_length=128, null=True, verbose_name="Address line 2"
                    ),
                ),
                (
                    "city",
                    models.CharField(blank=True, max_length=64, null=True, verbose_name="City"),
                ),
                (
                    "state",
                    models.CharField(blank=True, max_length=64, null=True, verbose_name="State"),
                ),
                (
                    "zip_code",
                    models.CharField(
                        blank=True,
                        max_length=10,
                        null=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Must be a valid zipcode in formats 19107 or 19107-3200",
                                regex="^(^[0-9]{5}(?:-[0-9]{4})?$|^$)",
                            )
                        ],
                    ),
                ),
                (
                    "petition",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="signatures",
                        to="campaigns.petition",
                    ),
                ),
            ],
        ),
    ]
