# Generated by Django 4.2.20 on 2025-03-21 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("campaigns", "0020_petitionsignature_location"),
    ]

    operations = [
        migrations.AddField(
            model_name="petition",
            name="call_to_action_header",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="petition",
            name="show_submissions",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="petition",
            name="letter",
            field=models.TextField(blank=True, null=True),
        ),
    ]
