# Generated by Django 4.2.20 on 2025-03-21 09:52

from django.db import migrations, models

import pbaabp.models


class Migration(migrations.Migration):

    dependencies = [
        ("campaigns", "0021_petition_call_to_action_header_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="petition",
            name="create_account_opt_in",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="petitionsignature",
            name="create_account_opt_in",
            field=models.BooleanField(default=False, verbose_name="Create a PBA Account"),
        ),
        migrations.AlterField(
            model_name="petition",
            name="signature_fields",
            field=pbaabp.models.ChoiceArrayField(
                base_field=models.CharField(
                    blank=True,
                    choices=[
                        ("first_name", "First Name"),
                        ("last_name", "Last Name"),
                        ("email", "E-mail"),
                        ("phone_number", "Phone Number"),
                        ("postal_address_line_1", "Street Address"),
                        ("postal_address_line_2", "Address Line 2"),
                        ("city", "City"),
                        ("state", "State"),
                        ("zip_code", "Zip Code"),
                        ("comment", "Comment"),
                    ],
                    max_length=128,
                    null=True,
                ),
                blank=True,
                null=True,
                size=None,
            ),
        ),
        migrations.AlterField(
            model_name="petitionsignature",
            name="postal_address_line_1",
            field=models.CharField(
                blank=True, max_length=128, null=True, verbose_name="Street Address"
            ),
        ),
        migrations.AlterField(
            model_name="petitionsignature",
            name="postal_address_line_2",
            field=models.CharField(
                blank=True, max_length=128, null=True, verbose_name="Address Line 2"
            ),
        ),
    ]
