# Generated by Django 4.2.20 on 2025-03-27 11:16

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("campaigns", "0022_petition_create_account_opt_in_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="campaign",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="campaign",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
