# Generated by Django 5.1.7 on 2025-03-28 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("campaigns", "0023_campaign_created_at_campaign_updated_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="petition",
            name="email_cc",
            field=models.TextField(blank=True, help_text="one per line", null=True),
        ),
        migrations.AlterField(
            model_name="petition",
            name="email_to",
            field=models.TextField(blank=True, help_text="one per line", null=True),
        ),
    ]
