# Generated by Django 5.1.7 on 2025-03-30 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("campaigns", "0024_alter_petition_email_cc_alter_petition_email_to"),
    ]

    operations = [
        migrations.AddField(
            model_name="campaign",
            name="social_shares",
            field=models.BooleanField(default=True),
        ),
    ]
