# Generated by Django 5.1.8 on 2025-06-04 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("campaigns", "0025_campaign_social_shares"),
    ]

    operations = [
        migrations.AddField(
            model_name="petition",
            name="redirect_after",
            field=models.URLField(
                blank=True, help_text="page to redirect to after signing", null=True
            ),
        ),
    ]
