# Generated by Django 5.1.8 on 2025-06-12 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("campaigns", "0026_petition_redirect_after"),
    ]

    operations = [
        migrations.AddField(
            model_name="petition",
            name="active",
            field=models.BooleanField(default=True),
        ),
    ]
