# Generated by Django 5.1.8 on 2025-06-04 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("maillinks", "0003_maillink_call_to_action_heading_maillink_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="maillink",
            name="bcc",
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
    ]
